# Generated by Django 5.1.2 on 2024-11-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_profilepic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for shipping', 'Out for shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='pending', max_length=150),
        ),
    ]
