# Generated by Django 5.1.2 on 2024-11-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
